baseURL: "https://codefrydev.in/design/"
languageCode: en-us
title: Code Fry Dev
theme: PaperMod
enableRobotsTXT: true

googleAnalytics: G-VM01Q3R43D
analytics:
    google:
      SiteVerificationTag: "G-VM01Q3R43D"
      
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: application
      name: App
      url: /application
      weight: 11
    - identifier: blog
      name: Design
      url: /blog
      weight: 11
    - identifier: games
      name: Game
      url: /games
      weight: 12
    - identifier: search
      name: Search
      url: /search
      weight: 50
    - identifier: tags
      name: Tag
      url: /tags
      weight: 60 
    - identifier: archives
      name: ARC
      url: /archives
      weight: 60 

params:
  math: true
  customCSS:
    - "css/custom.css"
  mainSections : ["blog","games","application"] # put parent directory to show in home pages
  images: ["android-chrome-512x512.png"]
  keywords: ["Blog", "CFD", "NET" ,"Tutorials","Design","Games"]
  description: "CodeFryDev is your ultimate destination for diverse digital content and tools. Enjoy our extensive game collection, innovative productivity apps, and micro applications for quick solutions. Access educational materials, interactive courses, and comprehensive tutorials for all skill levels. Fuel your creativity with design resources and versatile tools for efficient project completion. Visit CodeFryDev today and explore all we have to offer!"
  author: "CodeFryDev"
  defaultTheme: auto
  comments: true
  disqusShortname: codefrydev
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  hideDescriptionInList: false
  # for enchanced SEO
  env: production
  assets:
    disableHLJS: false
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "safari-pinned-tab.svg"
  label:
    text: "CFD Design"
    icon: "favicon.ico"
    iconHeight: 35


  # cover image for posts
  cover:
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:codefrydev@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/codefrydev"
    - name: "github"
      url: "https://github.com/codefrydev"
    - name: "youtube"
      url: "https://www.youtube.com/c/codefrydev"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      math: true
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    # noClasses: false
    style: vs
minify:
  disableXML: true
  minifyOutput: true